"""
Report Service

Generates a downloadable PDF report for Digital Wellness AI.
"""

from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from config.report_settings import REPORT_HIGHLIGHT_FEATURES


class ReportService:
    """
    Creates a downloadable PDF report.
    """

    def generate(
        self,
        user_data: dict,
        prediction_result,
        recommendations: list,
    ) -> BytesIO:

        buffer = BytesIO()
        document = SimpleDocTemplate(buffer)
        styles = getSampleStyleSheet()

        title_style = styles["Heading1"]
        title_style.alignment = TA_CENTER

        story = []

        story.append(Paragraph("Digital Wellness Report", title_style))
        story.append(Spacer(1, 20))
        story.append(
            Paragraph(
                f"Generated: {datetime.now():%Y-%m-%d %H:%M}",
                styles["Normal"],
            )
        )
        story.append(Spacer(1, 20))

        story.append(Paragraph("<b>Prediction Summary</b>", styles["Heading2"]))

        confidence_str = (
            f"{prediction_result.confidence:.1%}"
            if prediction_result.confidence is not None
            else "N/A"
        )

        summary = [
            ["Predicted Value / Status", str(prediction_result.prediction)],
            ["Confidence", confidence_str],
            ["Model Name", str(prediction_result.model_name)],
        ]

        table = Table(summary)
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
                    ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ]
            )
        )

        story.append(table)
        story.append(Spacer(1, 20))

        story.append(Paragraph("<b>User Input Highlights</b>", styles["Heading2"]))

        rows = [
            [feature.replace("_", " ").title(), str(user_data[feature])]
            for feature in REPORT_HIGHLIGHT_FEATURES
            if feature in user_data
        ]

        if rows:
            table_stats = Table(rows)
            table_stats.setStyle(
                TableStyle(
                    [
                        ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                        ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
                    ]
                )
            )
            story.append(table_stats)

        story.append(Spacer(1, 20))

        story.append(Paragraph("<b>Personalized Recommendations</b>", styles["Heading2"]))

        for rec in recommendations:
            story.append(
                Paragraph(
                    f"• <b>{rec.title}</b> ({rec.priority} Priority)<br/>{rec.description}<br/><i>Action: {rec.action}</i>",
                    styles["BodyText"],
                )
            )
            story.append(Spacer(1, 8))

        story.append(Spacer(1, 20))

        story.append(Paragraph("Generated by Digital Wellness AI", styles["Italic"]))

        document.build(story)
        buffer.seek(0)
        return buffer